apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-api
  template:
    metadata:
      labels:
        app: devops-api
    spec:
      containers:
        - name: devops-api
          image: docker.io/DOCKERHUB_USERNAME/devops-api-challenge:latest
          ports:
            - containerPort: 8000
          env:
            - name: DEVOPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: devops-api-secret
                  key: api-key
            - name: DEVOPS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: devops-api-secret
                  key: jwt-secret
          readinessProbe:
            httpGet:
              path: /DevOps
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /DevOps
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
